import type { Template, TemplateId } from '@/types/survey';

export const templates: Record<TemplateId, Template> = {
  'fine-dining': {
    id: 'fine-dining',
    name: '奶油金',
    nameEn: 'Elegant Gold',
    description: '溫潤奶油底色搭配金色調，高雅精緻',
    suited: '高級西餐、Fine Dining、法式料理',
    colors: {
      primary: '#C5A55A',
      primaryLight: '#E8D5A3',
      primaryDark: '#A08735',
      background: '#FAF7F2',
      surface: '#FFFFFF',
      text: '#4A4545',
      textLight: '#8A8585',
      border: '#E8E2D8',
      accent: '#B8926A',
    },
    fontHeading: "'Noto Serif TC', serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '16px',
    cardStyle: 'rounded',
  },

  'japanese': {
    id: 'japanese',
    name: '和風',
    nameEn: 'Zen',
    description: '淺米色搭配木質調，寧靜優雅',
    suited: '日料、壽司、居酒屋、拉麵',
    colors: {
      primary: '#8B7355',
      primaryLight: '#C4A882',
      primaryDark: '#6B5540',
      background: '#F5F0E8',
      surface: '#FDFBF7',
      text: '#3C3632',
      textLight: '#8A8078',
      border: '#E0D5C5',
      accent: '#C4A882',
    },
    fontHeading: "'Noto Serif TC', serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '8px',
    cardStyle: 'soft',
  },

  'industrial': {
    id: 'industrial',
    name: '工業風',
    nameEn: 'Industrial',
    description: '深色底搭配暖橘，粗獷有個性',
    suited: '酒吧、燒烤、美式餐廳、居酒屋',
    colors: {
      primary: '#D4A14A',
      primaryLight: '#E8C878',
      primaryDark: '#B8862E',
      background: '#1A1A1A',
      surface: '#2A2A2A',
      text: '#F0ECE0',
      textLight: '#A0A0A0',
      border: '#3A3A3A',
      accent: '#E8C878',
    },
    fontHeading: "'Noto Sans TC', sans-serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '4px',
    cardStyle: 'sharp',
  },

  'cafe': {
    id: 'cafe',
    name: '清新',
    nameEn: 'Fresh',
    description: '白底搭配草綠，清爽自然',
    suited: '早午餐、咖啡廳、輕食、蔬食',
    colors: {
      primary: '#6B9B76',
      primaryLight: '#A8C5A0',
      primaryDark: '#4A7A56',
      background: '#F8FAF5',
      surface: '#FFFFFF',
      text: '#3A4A3E',
      textLight: '#7A8A7E',
      border: '#D8E5D0',
      accent: '#A8C5A0',
    },
    fontHeading: "'Noto Sans TC', sans-serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '20px',
    cardStyle: 'rounded',
  },

  'chinese-classic': {
    id: 'chinese-classic',
    name: '古典紅',
    nameEn: 'Heritage Red',
    description: '暗紅搭配金字，典雅大氣',
    suited: '中餐廳、火鍋、台菜、宴會廳',
    colors: {
      primary: '#B22222',
      primaryLight: '#D4605A',
      primaryDark: '#8B1A1A',
      background: '#FFF8F0',
      surface: '#FFFFFF',
      text: '#3A2020',
      textLight: '#8A6A6A',
      border: '#E8D5CC',
      accent: '#D4A14A',
    },
    fontHeading: "'Noto Serif TC', serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '8px',
    cardStyle: 'soft',
  },

  'ocean': {
    id: 'ocean',
    name: '海洋藍',
    nameEn: 'Ocean Blue',
    description: '深海藍搭配珊瑚白，清爽透明感',
    suited: '海鮮餐廳、港口料理、水產、迴轉壽司',
    colors: {
      primary: '#1E6B8A',
      primaryLight: '#5BA4C4',
      primaryDark: '#0D4F6B',
      background: '#F0F7FA',
      surface: '#FFFFFF',
      text: '#1A3A4A',
      textLight: '#6A8A9A',
      border: '#D0E5EE',
      accent: '#E8925A',
    },
    fontHeading: "'Noto Sans TC', sans-serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '14px',
    cardStyle: 'rounded',
  },

  'night-market': {
    id: 'night-market',
    name: '夜市霓虹',
    nameEn: 'Neon Night',
    description: '深紫底搭配霓虹色，活潑夜生活感',
    suited: '夜市攤販、鹹酥雞、滷味、快炒、熱炒',
    colors: {
      primary: '#FF6B9D',
      primaryLight: '#FFB3CC',
      primaryDark: '#D94A7A',
      background: '#1A1028',
      surface: '#2A2038',
      text: '#F0E8FF',
      textLight: '#B0A0C8',
      border: '#3A2E50',
      accent: '#FFD700',
    },
    fontHeading: "'Noto Sans TC', sans-serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '12px',
    cardStyle: 'rounded',
  },

  'dessert': {
    id: 'dessert',
    name: '甜點粉',
    nameEn: 'Pastel Sweet',
    description: '柔和粉色搭配奶白，甜蜜夢幻感',
    suited: '甜點店、蛋糕、冰淇淋、下午茶、烘焙',
    colors: {
      primary: '#E88BA7',
      primaryLight: '#F5C6D4',
      primaryDark: '#C56A85',
      background: '#FFF5F8',
      surface: '#FFFFFF',
      text: '#4A2A35',
      textLight: '#9A7A85',
      border: '#F0D8E0',
      accent: '#D4A14A',
    },
    fontHeading: "'Noto Serif TC', serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '24px',
    cardStyle: 'rounded',
  },

  'korean': {
    id: 'korean',
    name: '韓潮',
    nameEn: 'K-Style',
    description: '黑白搭配螢光粉，潮流韓系風格',
    suited: '韓式料理、烤肉、炸雞、韓式炸物、部隊鍋',
    colors: {
      primary: '#FF4D6D',
      primaryLight: '#FF8FA3',
      primaryDark: '#D4324F',
      background: '#FAFAFA',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textLight: '#808080',
      border: '#E0E0E0',
      accent: '#FFD166',
    },
    fontHeading: "'Noto Sans TC', sans-serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '16px',
    cardStyle: 'rounded',
  },

  'bistro': {
    id: 'bistro',
    name: '餐酒館',
    nameEn: 'Bistro & Wine',
    description: '深酒紅搭配暖銅，微醺優雅氛圍',
    suited: '餐酒館、Wine Bar、義式小館、Tapas',
    colors: {
      primary: '#8B2252',
      primaryLight: '#C4667A',
      primaryDark: '#6B1A3E',
      background: '#1E1418',
      surface: '#2E2228',
      text: '#F0E0E5',
      textLight: '#B09098',
      border: '#3E2E35',
      accent: '#D4956A',
    },
    fontHeading: "'Noto Serif TC', serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '10px',
    cardStyle: 'soft',
  },

  'black-dragon': {
    id: 'black-dragon',
    name: '黑金龍',
    nameEn: 'Black Dragon',
    description: '黑底配粗紅邊框，金字奪目霸氣',
    suited: '燒烤、火鍋、中式料理、夜店餐廳',
    colors: {
      primary: '#D4A017',
      primaryLight: '#F0C842',
      primaryDark: '#A07B00',
      background: '#0D0D0D',
      surface: '#1A1A1A',
      text: '#F5D060',
      textLight: '#C09040',
      border: '#CC2200',
      accent: '#FF3300',
    },
    fontHeading: "'Noto Serif TC', serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '4px',
    cardStyle: 'sharp',
  },

  'wood-grain': {
    id: 'wood-grain',
    name: '木紋雅緻',
    nameEn: 'Wood Grain',
    description: '溫潤木紋底配粗金框，質樸雅致',
    suited: '日式料理、咖啡廳、木質裝潢餐廳',
    colors: {
      primary: '#D4A017',
      primaryLight: '#F0C842',
      primaryDark: '#A07800',
      background: '#3D2200',
      surface: '#5C3D1E',
      text: '#F5E8C0',
      textLight: '#C8A870',
      border: '#C5A55A',
      accent: '#F0C842',
    },
    fontHeading: "'Noto Serif TC', serif",
    fontBody: "'Noto Sans TC', sans-serif",
    borderRadius: '6px',
    cardStyle: 'soft',
  },
};

export const templateList = Object.values(templates);

export function getTemplate(id: TemplateId): Template {
  return templates[id] || templates['fine-dining'];
}

export function getThemeCSSVars(template: Template): Record<string, string> {
  const { colors } = template;
  return {
    '--color-primary': colors.primary,
    '--color-primary-light': colors.primaryLight,
    '--color-primary-dark': colors.primaryDark,
    '--color-bg': colors.background,
    '--color-surface': colors.surface,
    '--color-text': colors.text,
    '--color-text-light': colors.textLight,
    '--color-border': colors.border,
    '--color-accent': colors.accent,
    '--font-heading': template.fontHeading,
    '--font-body': template.fontBody,
    '--radius': template.borderRadius,
  };
}
